"""v10

Revision ID: 254bc04c870b
Revises: 975e5b02596a
Create Date: 2024-08-08 22:54:43.366555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '254bc04c870b'
down_revision = '975e5b02596a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keywords_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_company_table_keywords_id_keyword_table'), 'keyword_table', ['keywords_id'], ['id'])

    with op.batch_alter_table('keyword_table', schema=None) as batch_op:
        batch_op.drop_constraint('fk_keyword_table_companies_id_company_table', type_='foreignkey')
        batch_op.drop_column('companies_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keyword_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('companies_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_keyword_table_companies_id_company_table', 'company_table', ['companies_id'], ['id'])

    with op.batch_alter_table('company_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_company_table_keywords_id_keyword_table'), type_='foreignkey')
        batch_op.drop_column('keywords_id')

    # ### end Alembic commands ###
