"""v2

Revision ID: 6018fa66b4c2
Revises: fb5b7c0eb4e9
Create Date: 2024-08-08 20:20:10.020322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6018fa66b4c2'
down_revision = 'fb5b7c0eb4e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('keywords_table', sa.Column('type_id', sa.String(), nullable=True))
    # op.create_foreign_key(op.f('fk_keywords_table_type_id_types_table'), 'keywords_table', 'types_table', ['type_id'], ['id'])
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(op.f('fk_keywords_table_type_id_type_table'), 'keywords_table', type_='foreignkey')
    # op.drop_column('keywords_table', 'type_id')
    # ### end Alembic commands ###
    pass
