"""v7

Revision ID: 975e5b02596a
Revises: e3e5edf8dc8d
Create Date: 2024-08-08 21:39:39.863469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '975e5b02596a'
down_revision = 'e3e5edf8dc8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keyword_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('companies_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_keyword_table_companies_id_company_table'), 'company_table', ['companies_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keyword_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_keyword_table_companies_id_company_table'), type_='foreignkey')
        batch_op.drop_column('companies_id')

    # ### end Alembic commands ###
