"""v5

Revision ID: b148185ee9f7
Revises: 66532c14ab3b
Create Date: 2024-08-08 21:33:51.096167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b148185ee9f7'
down_revision = '66532c14ab3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_company_table_country_id_country_table'), 'country_table', ['country_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_company_table_country_id_country_table'), type_='foreignkey')
        batch_op.drop_column('country_id')

    # ### end Alembic commands ###
