"""WOOOO

Revision ID: c74552e3c41f
Revises: bc4ea388cbfd
Create Date: 2024-08-09 00:32:01.589398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c74552e3c41f'
down_revision = 'bc4ea388cbfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country_table', schema=None) as batch_op:
        batch_op.alter_column('abrv',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country_table', schema=None) as batch_op:
        batch_op.alter_column('abrv',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
