"""v6

Revision ID: e3e5edf8dc8d
Revises: b148185ee9f7
Create Date: 2024-08-08 21:35:05.321058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3e5edf8dc8d'
down_revision = 'b148185ee9f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_table', schema=None) as batch_op:
        batch_op.drop_constraint('fk_company_table_keywords_id_keyword_table', type_='foreignkey')
        batch_op.drop_column('keywords_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keywords_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_company_table_keywords_id_keyword_table', 'keyword_table', ['keywords_id'], ['id'])

    # ### end Alembic commands ###
